### ISSUE TITLE
Support to promises

### ISSUE THREAD

**Issue by I-NOZex** [benavern/z-modal#1]
Hi, i cannot find what type of license do you provide, so i'm asking here if i can adapt your code to support better integration with Javascript Promises, for use in  commercial project.
I will keep the credits for you of course, and i'll gladly, after finish the "Promise" integration, do a pull request.
I will wait for you reply, thanks.
If you don't understand what i mean, i can try to explain you in my poor french eh eh :)

**Comment by benavern** [comment]
Hey @I-NOZex 

I am glad you want to use what I hav done ! 
Of course you can use it and modify it for your needs for any project if you keep credits for me.
I am not used to provide some license and don't know which one to provide (Could you advise me so that I'll use it for all my other projects) 

I look forward to see what your pull request will look like!

Thank you for using my work, it is very valuable for me. 

By the same time, will I be able to see what you did wit it ?

Thanks in advance ;)

**Comment by I-NOZex** [comment]
I'm using your code to override the deafult system dialogs (alert, confirm, prompt).
The prompt was tricky because in the original code, all nodes are removed before the button callback, changind the order do the trick.

Well, about licenses i dont know much ahaha, i just know i can use MIT, Apache 2 and BSD without problems for commercial projects... But her's the sites i use when i'm with doubts: https://tldrlegal.com/ & http://choosealicense.com/licenses/ 
Most of the works like yours are licensed under MIT, so take a look and see if it fits ;)

**Comment by I-NOZex** [comment]
Relative to the promises, i resolved the problem in this way without need to change more of your code.

``` javascript
    window.prompt = function (msg, defaultVal, buttons) {
        var body =  '<p>' + msg + '</p>' +
                    '<div><input type="text" id="promptValue" value="' +
                    (defaultVal || '') + '"></div>';

        var getPrompt = new Promise(
            function(resolve) {
                var options = {
                    //autoload : false,
                    title: 'Fill the information',
                    content: body,
                    buttons: buttons ||
                    [
                        {
                            label: "OK",
                            half: true,
                            callback: function() {
                                resolve(document.getElementById('promptValue').value);
                            }
                        },
                        { label: "Cancel", half: true }
                    ]
                };

                new ZMODAL(options);
            }
        );

        return getPrompt;
    }
```

and then to get the value from prompt i use something like this: 

``` javascript
prompt('1 plus 1?').then(function(value) { console.log(value); }); 
```

I don't know much about Promises, but i've read this article https://developer.mozilla.org/pt-PT/docs/Web/JavaScript/Reference/Global_Objects/Promise and i think is the way to solve the problem to get values with custom dialogs.
If you know more about the subject i would to learn more.
Thanks!

**Comment by I-NOZex** [comment]
And to finalize, you're welcome.
I liked your plugin because has no dependencies and and few allow me use more than 2 buttons (that's the initial problem that i was to solve).
The final criteria that led me to choose was their recent update and the small size.

I would also suggest the possibility to setting the OnClose callback in a more generic way (invoking that callback also on the click of the overlay and close button), and also the possibility to disable the click event in the overlay (which still gave me problems ahah Solved with CSS, for incredible as it may seem)

``` css
.z-modal {
     pointer-events: none;
}

.z-modal * {
     pointer-events: all;
}
```

### Example of onClose callback implementation:

``` javascript
///(...)
var options = {
    onClose: callBeforeCloseMethod,
    ///(...)
};
///(...)
new ZMODAL(options);
///(...)
function callBeforeCloseMethod(){
    console.log('Looks like i went closed!?');
}
```

**Comment by benavern** [comment]
Wow, good job! 
I like your promise version!
For the overlay click, I coul'd add it as an option, but if you just want to disable it, you can delete lines 71 to 73. I think it'll be better that doing it in CSS because of the compatibility of the pointer-events property
for IE (http://caniuse.com/#search=pointer-events)

By the way, I thank you a lot for your contribution to this project! :)

**Comment by benavern** [comment]
I'll close this issue because I think it is solved... 
Don't hesitate to try and comment my other z-\* plugins. You can find some of them [HERE](http://labo.caradeuc.info) (where I used z-notif on the "?" on the top-right-corner)
Thank you again for your improvment solutions

**Comment by I-NOZex** [comment]
For me, the CSS solution isn't a problem because i'm working in a Node-Webkit app, so, it will be always Chrome(ium) engine :)

And you're welcome!
I'm happy to contribute.

And yes it is solved :) Thank you for this amazing plugin, when i have time i will check the others you have.
