### ISSUE TITLE
Documentation gone

### ISSUE THREAD

**Issue by Ailothaen** [benavern/z-modal#12]
Hello,

It seems the project documentation is gone (I see you changed the domain of your site, so that maybe explains why, but I cannot find it on the new website)

Could you upload it again and change the URL in this repository?

Thank you!

**Comment by benavern** [comment]
Hi, I'm glad to see that something I made 5 years ago and I had forgotten about is still useful for someone.

Here is the new documentation website link: https://benavern.github.io/z-modal/

Thank you for your interest in what I make :)
